//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Vendor { get; set; }
        public double Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public string Description { get; set; }
        public string PicPath { get; set; }
        public Nullable<int> Count { get; set; }
        public double WDis
        {
            get
            {
                return (Double)Price - (((Double)Price / 100) * (Double)Discount);
            }
        }
        public string Clr
        {
            get
            {
                if (Discount > 15)
                {
                    return "#aa33aa";
                }
                else
                {
                    return "#ffffff";
                }
            }
        }
    }
}
